/**
 * frontend/src/components/EvidenceCard.tsx
 * ─────────────────────────────────────────────────────────────────────────────
 * Displays the human-readable evidence text for an account's risk score.
 *
 * The evidence string is generated by scoring_explainer.py and explains:
 *   - Which signals fired and why they're suspicious
 *   - The scoring methodology applied
 *   - Multi-signal convergence if applicable
 *
 * This component formats the evidence text for readability:
 *   - Splits on semicolons to create bullet points
 *   - Highlights numeric values (dollar amounts, percentages, counts)
 *   - Provides a "Copy" button for pasting into SAR narratives
 * ─────────────────────────────────────────────────────────────────────────────
 */

import React, { useState } from 'react';

interface EvidenceCardProps {
  /** The evidence string from the backend */
  evidence: string | null | undefined;
  /** Account ID (used in copy action for context) */
  accountId: string;
}

export default function EvidenceCard({ evidence, accountId }: EvidenceCardProps) {
  const [copied, setCopied] = useState(false);

  if (!evidence) {
    return (
      <div className="bg-gray-900 border border-gray-800 rounded-xl p-4">
        <p className="text-gray-500 text-xs italic">No evidence text generated yet.</p>
      </div>
    );
  }

  // Split the evidence into sentences for better readability
  const sentences = evidence
    .split('. ')
    .map(s => s.trim())
    .filter(Boolean)
    .map(s => s.endsWith('.') ? s : s + '.');

  async function handleCopy() {
    const copyText = `Account: ${accountId}\n\n${evidence}`;
    try {
      await navigator.clipboard.writeText(copyText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API not available (non-HTTPS or permission denied)
    }
  }

  return (
    <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 space-y-3">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-xs text-gray-500 uppercase tracking-wide font-medium">
          Score Evidence
        </h3>
        <button
          onClick={handleCopy}
          className="text-xs text-gray-600 hover:text-gray-400 transition-colors flex items-center gap-1"
          aria-label="Copy evidence to clipboard"
        >
          {copied ? (
            <span className="text-green-400">✓ Copied</span>
          ) : (
            <span>📋 Copy</span>
          )}
        </button>
      </div>

      {/* Evidence sentences */}
      <div className="space-y-2">
        {sentences.map((sentence, idx) => (
          <p key={idx} className="text-xs text-gray-400 leading-relaxed">
            <HighlightedText text={sentence} />
          </p>
        ))}
      </div>
    </div>
  );
}

/**
 * Highlights numbers, dollar amounts, and percentages in the evidence text.
 * Makes it easier to quickly scan for the key quantitative findings.
 */
function HighlightedText({ text }: { text: string }) {
  // Pattern: $12,345 or 85.5% or "12 transactions" etc.
  const parts = text.split(/(\$[\d,]+(?:\.\d+)?|[\d.]+%|\b\d+\b)/g);

  return (
    <>
      {parts.map((part, i) => {
        const isNumber = /^(\$[\d,]+(?:\.\d+)?|[\d.]+%|\d+)$/.test(part);
        return isNumber ? (
          <span key={i} className="text-white font-medium">
            {part}
          </span>
        ) : (
          <span key={i}>{part}</span>
        );
      })}
    </>
  );
}
