/**
 * frontend/src/components/SignalTimeline.tsx
 * ─────────────────────────────────────────────────────────────────────────────
 * Vertical timeline of detection signals for an account.
 *
 * Each signal row shows:
 *   - Signal type icon + label
 *   - Horizontal score bar (0–100)
 *   - Confidence badge (high / medium / low)
 *   - Evidence text (the human-readable explanation generated by the rule)
 *
 * Signals are sorted by score descending so the most impactful appear first.
 *
 * This is a "read-only" display component — it receives signals as props
 * and has no internal state beyond rendering.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import React from 'react';
import { Signal } from '../api/client';

// ─── Signal type metadata ─────────────────────────────────────────────────────

/**
 * Human-readable labels and icons for each signal type.
 * The key matches the signal_type string returned by the backend.
 */
const SIGNAL_META: Record<string, { label: string; icon: string; colour: string }> = {
  structuring:      { label: 'Structuring',         icon: '🏦', colour: 'text-red-400'    },
  velocity:         { label: 'Velocity Anomaly',    icon: '⚡', colour: 'text-orange-400' },
  funnel:           { label: 'Funnel Account',      icon: '🔽', colour: 'text-yellow-400' },
  dormant_wakeup:   { label: 'Dormant Wakeup',      icon: '💤', colour: 'text-purple-400' },
  round_number:     { label: 'Round Numbers',       icon: '🔢', colour: 'text-blue-400'   },
  graph_pagerank:   { label: 'High Centrality',     icon: '🕸️', colour: 'text-pink-400'   },
  graph_community:  { label: 'Isolated Cluster',    icon: '🫧', colour: 'text-cyan-400'   },
  graph_cycle:      { label: 'Round-Trip Cycle',    icon: '🔄', colour: 'text-green-400'  },
  graph_chain:      { label: 'Layering Chain',      icon: '⛓️', colour: 'text-amber-400'  },
};

/** Fallback for unknown signal types */
const DEFAULT_META = { label: 'Unknown Signal', icon: '❓', colour: 'text-gray-400' };

// ─── Sub-components ───────────────────────────────────────────────────────────

/** Small badge for confidence level */
function ConfidenceBadge({ confidence }: { confidence: number }) {
  let label: string;
  let cls: string;

  if (confidence >= 0.8) {
    label = 'High';
    cls = 'bg-red-900 text-red-300 border-red-700';
  } else if (confidence >= 0.5) {
    label = 'Medium';
    cls = 'bg-yellow-900 text-yellow-300 border-yellow-700';
  } else {
    label = 'Low';
    cls = 'bg-gray-800 text-gray-400 border-gray-600';
  }

  return (
    <span className={`text-xs px-2 py-0.5 rounded-full border font-medium ${cls}`}>
      {label} confidence
    </span>
  );
}

/** Horizontal score bar — filled proportionally to score/100 */
function ScoreBar({ score, colour }: { score: number; colour: string }) {
  // Map Tailwind text colour class to a background class
  // (we strip "text-" prefix and add "bg-")
  const bgClass = colour.replace('text-', 'bg-');

  return (
    <div className="flex items-center gap-3">
      <div className="flex-1 bg-gray-800 rounded-full h-2 overflow-hidden">
        <div
          className={`h-full rounded-full ${bgClass} transition-all duration-700`}
          style={{ width: `${score}%` }}
        />
      </div>
      <span className={`text-sm font-bold font-mono w-8 text-right ${colour}`}>
        {score}
      </span>
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

interface SignalTimelineProps {
  /** Array of signals from the backend for this account */
  signals: Signal[];
}

export default function SignalTimeline({ signals }: SignalTimelineProps) {
  if (signals.length === 0) {
    return (
      <div className="text-center py-8 text-gray-500 text-sm">
        No signals detected for this account.
      </div>
    );
  }

  // Sort signals: highest score first so most impactful rule is at the top
  const sorted = [...signals].sort((a, b) => b.score - a.score);

  return (
    <div className="space-y-4">
      {sorted.map((signal, idx) => {
        const meta = SIGNAL_META[signal.signal_type] ?? DEFAULT_META;

        return (
          <div
            key={signal.signal_id ?? idx}
            className="bg-gray-900 border border-gray-800 rounded-xl p-4 space-y-3"
          >
            {/* Header row: icon + label + confidence badge */}
            <div className="flex items-center justify-between flex-wrap gap-2">
              <div className="flex items-center gap-2">
                <span className="text-xl" role="img" aria-label={meta.label}>
                  {meta.icon}
                </span>
                <span className={`font-semibold text-sm ${meta.colour}`}>
                  {meta.label}
                </span>
                <span className="text-gray-600 text-xs font-mono">
                  (weight {signal.weight.toFixed(1)})
                </span>
              </div>
              <ConfidenceBadge confidence={signal.confidence} />
            </div>

            {/* Score bar */}
            <ScoreBar score={signal.score} colour={meta.colour} />

            {/* Evidence text */}
            <p className="text-gray-400 text-xs leading-relaxed">
              {signal.evidence}
            </p>
          </div>
        );
      })}
    </div>
  );
}
