"""
backend/database/schema.py
─────────────────────────────────────────────────────────────────────────────
Defines the database tables using SQLAlchemy ORM (Object-Relational Mapper).

What is an ORM?
    Instead of writing raw SQL like:
        CREATE TABLE accounts (id TEXT, name TEXT, ...)
    We define Python classes, and SQLAlchemy turns them into SQL automatically.
    This is safer (no SQL injection) and more readable.

What database are we using?
    SQLite — a single file database (data/aml.db).
    No server needed. Perfect for development and portfolio projects.
─────────────────────────────────────────────────────────────────────────────
"""

# SQLAlchemy imports — these are the building blocks for defining tables
from sqlalchemy import (
    Column,        # defines a table column
    String,        # text data type
    Float,         # decimal number (for amounts)
    Integer,       # whole number
    Boolean,       # true/false (for is_suspicious flags)
    DateTime,      # date + time
    Text,          # long text (for evidence strings)
    ForeignKey,    # links one table to another
    Index,         # speeds up database searches
    create_engine  # creates the database connection
)
from sqlalchemy.orm import DeclarativeBase, relationship, sessionmaker
from datetime import datetime


# ─── Base class ───────────────────────────────────────────────────────────────
# All our table classes inherit from this Base.
# SQLAlchemy uses Base to track which classes represent tables.

class Base(DeclarativeBase):
    """Parent class for all database table definitions."""
    pass


# ─── ACCOUNTS TABLE ───────────────────────────────────────────────────────────

class Account(Base):
    """
    Represents one bank account.

    Every person in our simulation has one Account.
    Accounts can be:
      - Legitimate (normal customers)
      - Dirty (involved in one of the 6 typologies)

    Ground truth: we know which accounts are dirty because we generated them.
    In real life, you don't know this ahead of time — that's the challenge!
    """

    __tablename__ = "accounts"  # the actual SQL table name

    # Primary key — unique identifier for each account
    # Format: "ACC_000001", "ACC_000002", etc.
    account_id = Column(String, primary_key=True)

    # Account holder's full name (generated by Faker)
    holder_name = Column(String, nullable=False)

    # What kind of account (checking, savings, business)
    account_type = Column(String, nullable=False)

    # Where the account is held (bank branch location)
    branch = Column(String, nullable=False)

    # When the account was opened
    opened_date = Column(DateTime, nullable=False)

    # Account balance in USD
    balance = Column(Float, nullable=False, default=0.0)

    # ── Ground truth labels (set by the generator) ──────────────────────────
    # is_suspicious: True if this account is involved in money laundering
    is_suspicious = Column(Boolean, nullable=False, default=False)

    # typology: which pattern this account represents, or "benign"
    # Values: "structuring", "layering", "funnel", "round_trip",
    #         "shell_company", "velocity", "benign"
    typology = Column(String, nullable=False, default="benign")

    # ── Risk scores (set by the detection pipeline) ──────────────────────────
    # Current risk score 0-100 (100 = most suspicious)
    risk_score = Column(Float, nullable=True, default=None)

    # Evidence string: human-readable explanation of why this score was given
    # Example: "12 deposits avg $9,640 across 9 days (structuring, conf 87%)"
    evidence = Column(Text, nullable=True, default=None)

    # When the risk score was last calculated
    scored_at = Column(DateTime, nullable=True, default=None)

    # ── Analyst disposition ─────────────────────────────────────────────────
    # What did the analyst decide?
    # Values: None (unreviewed), "escalated", "dismissed"
    disposition = Column(String, nullable=True, default=None)

    # Analyst's note explaining their decision
    disposition_note = Column(Text, nullable=True, default=None)

    # When the analyst made their decision
    disposition_at = Column(DateTime, nullable=True, default=None)

    # ── Relationships ─────────────────────────────────────────────────────────
    # This tells SQLAlchemy: "an account has many transactions"
    # We can then do: account.transactions_sent to get all sent transactions
    transactions_sent = relationship(
        "Transaction",
        foreign_keys="Transaction.sender_account_id",
        back_populates="sender"
    )
    transactions_received = relationship(
        "Transaction",
        foreign_keys="Transaction.receiver_account_id",
        back_populates="receiver"
    )


# ─── TRANSACTIONS TABLE ───────────────────────────────────────────────────────

class Transaction(Base):
    """
    Represents one financial transaction (one transfer of money).

    Every time money moves from one account to another, we record a Transaction.
    The transaction graph is built from these records.
    """

    __tablename__ = "transactions"

    # Unique transaction ID
    # Format: "TX_00000001", "TX_00000002", etc.
    transaction_id = Column(String, primary_key=True)

    # Which account sent the money
    sender_account_id = Column(
        String,
        ForeignKey("accounts.account_id"),  # must match an account_id in accounts table
        nullable=False
    )

    # Which account received the money
    receiver_account_id = Column(
        String,
        ForeignKey("accounts.account_id"),
        nullable=False
    )

    # How much money was transferred (USD)
    amount = Column(Float, nullable=False)

    # What kind of transaction
    # Values: "cash_deposit", "wire_transfer", "ach", "internal_transfer", "atm"
    transaction_type = Column(String, nullable=False)

    # Short description (like a check memo)
    # Example: "rent payment", "payroll deposit", "consulting fees"
    description = Column(String, nullable=False)

    # When the transaction happened (date + time)
    transaction_date = Column(DateTime, nullable=False)

    # ── Ground truth ────────────────────────────────────────────────────────
    # True if this transaction is part of a suspicious pattern
    is_suspicious = Column(Boolean, nullable=False, default=False)

    # Which typology this transaction belongs to, or "benign"
    typology = Column(String, nullable=False, default="benign")

    # ── Relationships ────────────────────────────────────────────────────────
    sender = relationship(
        "Account",
        foreign_keys=[sender_account_id],
        back_populates="transactions_sent"
    )
    receiver = relationship(
        "Account",
        foreign_keys=[receiver_account_id],
        back_populates="transactions_received"
    )


# ─── SIGNALS TABLE ────────────────────────────────────────────────────────────

class Signal(Base):
    """
    Stores one detection signal for one account.

    When a detection rule fires on an account, we store the signal here.
    Multiple signals can exist per account (e.g., both structuring AND velocity).

    This lets us:
      1. Debug why a score was assigned
      2. Calculate false positive rates per rule
      3. Build the evidence string for analysts
    """

    __tablename__ = "signals"

    # Auto-incrementing ID (SQLite generates this automatically)
    signal_id = Column(Integer, primary_key=True, autoincrement=True)

    # Which account this signal is for
    account_id = Column(
        String,
        ForeignKey("accounts.account_id"),
        nullable=False
    )

    # Which rule or graph signal generated this
    # Examples: "structuring_rule", "velocity_rule", "graph_pagerank"
    signal_type = Column(String, nullable=False)

    # Score for THIS signal only (0-100)
    # The final account score is a weighted combination of all its signals
    score = Column(Float, nullable=False)

    # Weight of this signal in the final score calculation
    weight = Column(Float, nullable=False, default=1.0)

    # Human-readable explanation of why this signal fired
    evidence = Column(Text, nullable=False)

    # Confidence level 0.0 to 1.0
    confidence = Column(Float, nullable=False)

    # When this signal was generated
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)


# ─── DISPOSITIONS TABLE ───────────────────────────────────────────────────────

class Disposition(Base):
    """
    Stores analyst decisions over time.

    Keeping a history of decisions lets us:
      - Calculate analyst accuracy (did their dismissals turn out to be wrong?)
      - Track false positive rate per rule
      - Build a feedback loop for improving detection
    """

    __tablename__ = "dispositions"

    disposition_id = Column(Integer, primary_key=True, autoincrement=True)

    account_id = Column(
        String,
        ForeignKey("accounts.account_id"),
        nullable=False
    )

    # "escalated" or "dismissed"
    decision = Column(String, nullable=False)

    # What the risk score was when the decision was made
    risk_score_at_decision = Column(Float, nullable=False)

    # Analyst's reasoning
    note = Column(Text, nullable=True)

    decided_at = Column(DateTime, nullable=False, default=datetime.utcnow)


# ─── Database indexes ─────────────────────────────────────────────────────────
# Indexes speed up searches. Without them, SQLite reads every row.
# With them, it jumps directly to matching rows.

# Makes "find all transactions for account X" fast
Index("idx_tx_sender",   Transaction.sender_account_id)
Index("idx_tx_receiver", Transaction.receiver_account_id)
Index("idx_tx_date",     Transaction.transaction_date)

# Makes sorting accounts by risk score fast (for the queue)
Index("idx_acc_risk",    Account.risk_score)
Index("idx_acc_typology", Account.typology)

# Makes finding signals by account fast
Index("idx_sig_account", Signal.account_id)


# ─── Database connection helpers ──────────────────────────────────────────────

def get_engine(db_path: str = "data/aml.db"):
    """
    Create and return a SQLAlchemy engine connected to our SQLite database.

    The engine is the "connection factory" — it manages the actual database file.

    Args:
        db_path: Path to the SQLite file (relative to project root)

    Returns:
        SQLAlchemy engine object

    Example:
        engine = get_engine()
        # Now we can create tables or run queries with this engine
    """
    # "sqlite:///" prefix tells SQLAlchemy to use SQLite
    # echo=False means don't print every SQL query (set to True for debugging)
    return create_engine(f"sqlite:///{db_path}", echo=False)


def create_all_tables(engine):
    """
    Create all tables in the database if they don't exist.

    Safe to call multiple times — won't erase existing data,
    just creates missing tables.

    Args:
        engine: SQLAlchemy engine from get_engine()
    """
    Base.metadata.create_all(engine)  # creates all tables defined above


def get_session_factory(engine):
    """
    Create a session factory for database transactions.

    A "session" is like a temporary workspace — you load data into it,
    make changes, then "commit" (save) or "rollback" (undo).

    Args:
        engine: SQLAlchemy engine from get_engine()

    Returns:
        Session class — call Session() to create a new session

    Example:
        Session = get_session_factory(engine)
        with Session() as session:
            account = session.get(Account, "ACC_000001")
            account.risk_score = 85.0
            session.commit()
    """
    return sessionmaker(bind=engine)
